import re
from typing import Type

from crewai.tools import BaseTool
from pydantic import BaseModel, Field


MOCK_RULE_LIBRARY: dict[str, list[dict[str, object]]] = {
    "需求": [
        {
            "violation": "需求真实性不足",
            "keywords": ["需求不明确", "需求模糊", "客户还没想清楚", "只是了解一下"],
            "risk_hint": "需求尚未被客户明确，后续动作容易建立在错误假设上。",
        },
        {
            "violation": "预算没有落位",
            "keywords": ["没有预算", "预算未批", "预算不明确", "还没立项"],
            "risk_hint": "预算未落位时，推进节奏和优先级都存在较大不确定性。",
        },
    ],
    "技术认可": [
        {
            "violation": "技术验证尚未完成",
            "keywords": ["没有测试", "还没测试", "POC未做", "未验证"],
            "risk_hint": "没有技术验证背书时，方案可信度和中标稳定性较弱。",
        },
        {
            "violation": "客户对方案存在明确质疑",
            "keywords": ["不认可", "质疑方案", "担心效果", "怀疑稳定性"],
            "risk_hint": "技术认可度不足会直接削弱后续商务和决策层推动。",
        },
    ],
    "决策链": [
        {
            "violation": "决策链缺失关键KP",
            "keywords": ["决策人不清楚", "关键人不清楚", "找不到拍板人", "不知道谁拍板"],
            "risk_hint": "关键决策角色未识别时，动作容易打在错误对象上。",
        },
        {
            "violation": "高层关系未建立",
            "keywords": ["还没见领导", "高层没接触", "没有高层通道", "接触不到决策层"],
            "risk_hint": "缺少高层通道会让项目在关键节点失去校准和推动能力。",
        },
    ],
    "竞争对手": [
        {
            "violation": "竞争对手已被锁定",
            "keywords": ["竞对已锁定", "友商已锁定", "内定竞争对手", "对手关系很深"],
            "risk_hint": "对手若已完成关键卡位，常规跟进动作很难逆转局势。",
        },
        {
            "violation": "对手已占据技术或关系优势",
            "keywords": ["对手领先", "客户倾向竞对", "竞对关系更深", "标准偏向竞对"],
            "risk_hint": "若对手已占优，必须优先识别其卡位点和我方破局窗口。",
        },
    ],
    "合作伙伴": [
        {
            "violation": "合作伙伴立场不稳",
            "keywords": ["伙伴不支持", "渠道不投入", "伙伴偏向别人", "合作伙伴态度模糊"],
            "risk_hint": "合作伙伴若立场不稳，信息链和协同执行都可能失真。",
        },
        {
            "violation": "协同责任不清晰",
            "keywords": ["分工不清", "责任不清", "口径不一致", "没人负责"],
            "risk_hint": "协同责任不清会导致现场动作失焦、客户感知混乱。",
        },
    ],
    "流程": [
        {
            "violation": "流程窗口可能已经错过",
            "keywords": ["快发标了", "已经发标", "窗口很短", "时间来不及"],
            "risk_hint": "流程窗口收窄时，影响标准、预算或关键人的空间会急剧下降。",
        },
        {
            "violation": "采购路径受限",
            "keywords": ["必须招标", "资质卡住", "本地化要求", "付款条件很苛刻"],
            "risk_hint": "采购路径受限会把项目风险从关系和方案层推向合规与执行层。",
        },
    ],
}

BAN_WORDS = [
    "加强沟通",
    "建立信任",
    "持续跟进",
    "深入了解",
    "保持联系",
    "提高警惕",
]

PLACEHOLDER_VALUES = {
    "",
    "...",
    "…",
    "待补充",
    "暂无",
    "tbd",
    "n/a",
    "na",
}

ACTION_FIELD_PATTERNS: dict[str, list[re.Pattern[str]]] = {
    "动作": [
        re.compile(r"(?is)(?:^|\|)\s*动作\s*[:：]\s*([^|\n]+)"),
        re.compile(r"(?is)(?:^|\|)\s*(?:Action|Do\s*What)\s*[:：]\s*([^|\n]+)"),
    ],
    "时间期限": [
        re.compile(r"(?is)(?:^|\|)\s*时间期限\s*[:：]\s*([^|\n]+)"),
        re.compile(r"(?is)(?:^|\|)\s*(?:时间|截止时间|最晚时间|Deadline|When)\s*[:：]\s*([^|\n]+)"),
    ],
    "对象": [
        re.compile(r"(?is)(?:^|\|)\s*对象\s*[:：]\s*([^|\n]+)"),
        re.compile(r"(?is)(?:^|\|)\s*(?:Target|Who)\s*[:：]\s*([^|\n]+)"),
    ],
    "目的": [
        re.compile(r"(?is)(?:^|\|)\s*目的\s*[:：]\s*([^|\n]+)"),
        re.compile(r"(?is)(?:^|\|)\s*(?:Goal|Purpose)\s*[:：]\s*([^|\n]+)"),
    ],
}


class CheckRuleViolationsInput(BaseModel):
    """Input payload for rule-violation detection.

    Attributes:
        project_status: Sales project status text covering one or more six-element dimensions.
    """

    project_status: str = Field(..., description="当前销售项目六要素现状描述。")


class ActionFormatValidatorInput(BaseModel):
    """Input payload for final action format validation.

    Attributes:
        action_text: One sales action generated by the closer agent.
    """

    action_text: str = Field(..., description="收口人生成的单条销售动作文本。")


class ActionExecutabilityCheckInput(BaseModel):
    """Input payload for action executability scanning.

    Attributes:
        action_text: One sales action generated by the closer agent.
    """

    action_text: str = Field(..., description="收口人生成的单条销售动作文本。")


class CheckRuleViolationsTool(BaseTool):
    """Detect six-element rule violations from project status text.

    This tool is intended for the Diagnostician agent. It uses a mocked
    in-memory rule library to scan the project status for common sales red
    flags such as missing decision makers, absent budget, or competitors
    already locked in.

    Args:
        project_status: Free-form description of the current sales project.

    Returns:
        A structured plain-text summary listing detected violations grouped by
        dimension, or a no-violation message when nothing is matched.

    Limitations:
        This version only performs simple keyword matching and does not rely on
        Excel ingestion or semantic classification.
    """

    name: str = "check_rule_violations"
    description: str = (
        "检测当前项目是否触碰六要素红线。适用于诊断阶段，快速识别预算未落位、"
        "关键人不清楚、竞争对手已锁定、流程窗口错过等高风险违规项。"
    )
    args_schema: Type[BaseModel] = CheckRuleViolationsInput

    def _run(self, project_status: str) -> str:
        """Scan the project status text against the mocked rule library.

        Args:
            project_status: Sales project description text to inspect.

        Returns:
            A structured result string containing violations or a no-issue
            message. Returns a stable error string if the input is invalid.
        """
        try:
            normalized = project_status.strip()
            if not normalized:
                return "Check Rule Violations Error: project_status 不能为空。"

            matched_lines: list[str] = []
            for dimension, rules in MOCK_RULE_LIBRARY.items():
                dimension_hits: list[str] = []
                lowered_text = normalized.lower()
                for rule in rules:
                    keywords = [str(keyword) for keyword in rule["keywords"]]
                    hit_keywords = [
                        keyword for keyword in keywords if keyword.lower() in lowered_text
                    ]
                    if not hit_keywords:
                        continue

                    dimension_hits.append(
                        "\n".join(
                            [
                                f"- 违规项：{rule['violation']}",
                                f"  触发依据：{', '.join(hit_keywords)}",
                                f"  风险提示：{rule['risk_hint']}",
                            ]
                        )
                    )

                if dimension_hits:
                    matched_lines.append(f"[{dimension}]\n" + "\n".join(dimension_hits))

            if not matched_lines:
                return "已识别的违规项：无明显违规"

            return "已识别的违规项：\n" + "\n\n".join(matched_lines)
        except Exception as error:
            return f"Check Rule Violations Error: {error}"


class ActionFormatValidatorTool(BaseTool):
    """Validate whether one sales action contains the required four fields.

    This tool is intended for the Closer agent. It verifies that one action
    clearly contains 动作、时间期限、对象、目的 in the new closer contract,
    and it rejects placeholder-only values.

    Args:
        action_text: One candidate sales action from the closer output.

    Returns:
        ``Format Valid: True`` when all fields are present and non-empty;
        otherwise a plain-text error message describing the missing fields.
    """

    name: str = "action_format_validator"
    description: str = (
        "校验单条销售动作是否完整包含 动作、时间期限、对象、目的，"
        "兼容常见别名如时间、截止时间、Who、When、Goal。"
    )
    args_schema: Type[BaseModel] = ActionFormatValidatorInput

    def _run(self, action_text: str) -> str:
        """Validate the presence and minimal content of the required fields.

        Args:
            action_text: One closer-generated action string.

        Returns:
            A pass/fail plain-text validation result. Returns a stable error
            string if unexpected processing fails.
        """
        try:
            normalized = action_text.strip()
            if not normalized:
                return (
                    "Format Valid: False. Missing: [动作, 时间期限, 对象, 目的]. "
                    "请补充具体动作、最晚时间或阶段窗口、对应对象和本次动作要验证或推进的目的。"
                )

            missing_fields = [
                field_name
                for field_name, patterns in ACTION_FIELD_PATTERNS.items()
                if not any(
                    _is_meaningful_value(match.group(1))
                    for pattern in patterns
                    if (match := pattern.search(normalized))
                )
            ]
            if not missing_fields:
                return "Format Valid: True"

            field_hints = {
                "动作": "请补充具体可执行动作。",
                "时间期限": "请补充明确的最晚时间、阶段窗口或截止时点。",
                "对象": "请补充动作对应的关键对象。",
                "目的": "请补充本次动作想验证、推进或锁定的目标。",
            }
            hints = " ".join(field_hints[field_name] for field_name in missing_fields)
            return f"Format Valid: False. Missing: {missing_fields}. {hints}"
        except Exception as error:
            return f"Format Validation Error: {error}"


class ActionExecutabilityCheckTool(BaseTool):
    """Detect vague action wording that makes a sales step hard to execute.

    This tool is intended for the Closer agent. It scans a single action for
    banned vague phrases such as ``加强沟通`` or ``持续跟进`` and asks the model
    to replace them with concrete, time-bound behavior.

    Args:
        action_text: One candidate sales action from the closer output.

    Returns:
        ``Action Executable: True`` when no vague wording is found; otherwise a
        warning message naming the hit phrases and requesting a more concrete
        action.
    """

    name: str = "action_executability_check"
    description: str = (
        "检查单条动作是否包含“加强沟通”“持续跟进”这类假大空词汇，"
        "帮助收口阶段把抽象建议改成可执行动作。"
    )
    args_schema: Type[BaseModel] = ActionExecutabilityCheckInput

    def _run(self, action_text: str) -> str:
        """Scan for banned vague phrases in one action string.

        Args:
            action_text: One closer-generated action string.

        Returns:
            A pass/fail plain-text executability result. Returns a stable error
            string if unexpected processing fails.
        """
        try:
            normalized = action_text.strip()
            if not normalized:
                return (
                    "Executability Warning: 动作为空，动作不可执行，请补充具体动作"
                    "（例如：今天下午给客户打一通 5 分钟电话确认需求细节）。"
                )

            hit_words = [word for word in BAN_WORDS if word in normalized]
            if not hit_words:
                return "Action Executable: True"

            return (
                f"Executability Warning: 包含空泛词汇 {hit_words}，动作不可执行，请修改为具体的动作"
                "（例如：打一通5分钟电话确认需求细节）。"
            )
        except Exception as error:
            return f"Action Executability Check Error: {error}"


def build_core_sales_tools() -> dict[str, BaseTool]:
    """Build the shared business validation tools for sales agents.

    Returns:
        A dictionary of instantiated CrewAI tools keyed by stable internal
        names, ready to be mounted onto Diagnostician and Closer agents.
    """

    return {
        "check_rule_violations": CheckRuleViolationsTool(),
        "action_format_validator": ActionFormatValidatorTool(),
        "action_executability_check": ActionExecutabilityCheckTool(),
    }


def _is_meaningful_value(value: str) -> bool:
    """Check whether a matched action field contains real content."""

    compact = value.strip().strip("|").strip()
    if compact.lower() in PLACEHOLDER_VALUES:
        return False

    compact = re.sub(r"[\s:：\-_.|/]+", "", compact)
    if not compact:
        return False

    return compact.lower() not in PLACEHOLDER_VALUES
